// <auto-generated />
namespace ProduitsApp.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Creationinitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Creationinitial));
        
        string IMigrationMetadata.Id
        {
            get { return "201804251437021_Creation initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
